# services:
#   mongodb:
#     build: ./mongodb  # build is used to look for ./mongodb dockerfile inside my local docker repository.
#     image: mongodb:v1
#     container_name: mongodb
#     volumes: 
#     - mongodb:/data/db
#   catalogue:
#     build: ./catalogue
#     image: catalogue:v1
#     container_name: catalogue
#     depends_on:
#     - mongodb
#   redis:
#     image: redis:7.0
#     container_name: redis
#     volumes: 
#     - redis:/data
#   mysql:
#     build: ./mysql
#     image: mysql:v1
#     container_name: mysql
#     volumes: 
#     - mysql:/var/lib/mysql
#   rabbitmq:
#     build: ./rabbitmq
#     image: rabbitmq:v1
#     container_name: rabbitmq
#     volumes:
#     - rabbitmq:/var/lib/rabbitmq
#   # environment:
#   #   RABBITMQ_DEFAULT_USER: "roboshop"
#   #   RABBITMQ_DEFAULT_PASS: "roboshop123"
#   user:
#     build: ./user
#     image: user:v1
#     container_name: user
#     depends_on:
#     - mongodb
#     - redis
#   cart:
#     build: ./cart
#     image: cart:v1
#     container_name: cart
#     depends_on:
#     - catalogue
#     - redis
#   shipping:
#     build: ./shipping
#     image: shipping:v1
#     container_name: shipping
#     depends_on:
#     - cart
#     - mysql
#   payment:
#     build: ./payment
#     image: payment:v1
#     container_name: payment
#     depends_on:
#     - cart
#     - user
#     - rabbitmq
#   frontend:
#     build: ./frontend
#     image: frontend:v1
#     container_name: frontend
#     # docker-compose supports only ports BUT NOT vars (If I am trying to provide vars)
#     # vars are allowed in ansible playbooks
#     ports:  
#       - "8012:80"
#     depends_on:
#     - catalogue
#     - user
#     - cart
#     - shipping
#     - payment  
# networks:
#   default:
#     driver: bridge
#     name: roboshop
#     external: false  # true if you have created n/w manually using docker n/w command
#                      #  false if I am creating docker n/w using  docker-compose.yaml file
# volumes: 
#   mongodb:    # it is equaivalent to "docker volume create mongodb" command 
#   redis:
#   mysql:
#   rabbitmq:
  
services:
  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    image: joindevops/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  mongodb:
    build: ./mongodb
    image: joindevops/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
    - redis:/data
  mysql:
    build: ./mysql
    image: joindevops/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes: # -v rabbitmq:/var/lib/rabbitmq
    - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  user:
    build: ./user
    image: joindevops/user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    build: ./cart
    image: joindevops/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  shipping:
    build: ./shipping
    image: joindevops/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  payment:
    build: ./payment
    image: joindevops/payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
    - cart
    - user
  frontend:
    build: ./frontend
    image: joindevops/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment
  networks:
    default:
      driver: bridge
      name: roboshop
      external: false # true if you have created network manually using docker network command
  volumes:
    mongodb: # docker volume create mongodb. /var/lib/docker/volumes
    redis:
    mysql:
    rabbitmq:



