services:
  mongodb:
    image: muddanadevops/mongodb:v1
    container_name: mongodb
  catalogue:
    image: muddanadevops/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: muddanadevops/redis:7.0
    container_name: redis
  mysql:
    image: muddanadevops/mysql:v1
    container_name: mysql
  rabbitmq:
    image: muddanadevops/rabbitmq:v1
    container_name: rabbitmq
  # environment:
  #   RABBITMQ_DEFAULT_USER: "roboshop"
  #   RABBITMQ_DEFAULT_PASS: "roboshop123"
  user:
    image: muddanadevops/user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    image: muddanadevops/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  shipping:
    image: muddanadevops/shipping:v1
    container_name: shipping
    depends_on:
    - cart
    - mysql
  payment:
    image: muddanadevops/payment:v1
    container_name: payment
    depends_on:
    - cart
    - user
    - rabbitmq
  frontend:
    image: muddanadevops/frontend:v1
    container_name: frontend
    # docker-compose supports only ports BUT NOT vars (If I am trying to provide vars)
    # vars are allowed in ansible playbooks
    ports:  
      - "8012:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment  
networks:
  default:
    driver: bridge
    name: roboshop
    external: true  # true if you have created n/w manually using docker n/w command
    



